### ISSUE TITLE
pytyndall installs in wrong directory on honister

### ISSUE THREAD

**Issue by johannesschrimpf** [BluEye-Robotics/tyndall#3]
In honister, pytyndall installs in `/usr/lib/python3/dist-packages/` whic is not imported by python.

The other libraries like pyblunux install in `/usr/lib/python3.9/site-packages`.

We should add the same mechanism as in libblunux:
Example from libblunux recipe:
```
EXTRA_OECMAKE = "-DPY_SITE_PATH=${PYTHON_SITEPACKAGES_DIR}"
```

Example from pyblunux CMakeLists.txt:
```
if (NOT DEFINED PY_SITE_PATH)
  set (PY_SITE_PATH ${Python3_SITELIB})
endif()
install(TARGETS pyblunux DESTINATION ${PY_SITE_PATH} OPTIONAL)
```

**Comment by erlenner** [comment]
Python support removed in e79388d8f4c57a32ab0e998d5a0f3896601c4d2c, pending removal of the p2_drone depth node in python: https://github.com/BluEye-Robotics/p2_drone/blob/dev/src/node_sensor_depth.py
